server:
  port: 8888

spring:
  application:
    name: config-server-app
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
      server:
        native:
          searchLocations: file:///${user.home}/git-repositories/microservices-spring-cloud-netflix/config-data